language: d

before_script:
  - dub fetch doveralls
  - dub fetch ddox

script:
  # Coverage disabled due to
  # https://github.com/rejectedsoftware/vibe.d/issues/767
  # - dub test --config=unittest --coverage
  - dub test --config=unittest

after_success:
  - dub run doveralls
